FROM python:3.13.2-slim

# 设置环境变量以减少缓存和输出
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

# 设置工作目录
WORKDIR /app

# 安装 Python 依赖
COPY requirements-cpu.txt .
RUN pip install --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements-cpu.txt


# 复制项目文件
COPY . .

# 暴露端口
EXPOSE 7860

# 设置默认运行命令
CMD ["python", "BFDS_web.py"]