name: auto docker

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest tag
        id: get_latest_tag
        run: |
          # 获取最新的标签
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0")
          echo "Latest tag: $latest_tag"

          # 提取主版本号并递增
          version=$(echo $latest_tag | grep -oE '[0-9]+\.[0-9]+' || echo "0.0")
          major=$(echo $version | cut -d. -f1)
          new_major=$((major + 1))
          new_version="${new_major}.0"

          # 输出新版本号
          echo "New version: $new_version"
          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Build and push CPU Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.cpu
          push: true
          tags: |
            ghcr.io/bfds-project/bearing-fault-diagnosis-system-webui:cpu-${{ env.new_version }}
            ghcr.io/bfds-project/bearing-fault-diagnosis-system-webui:cpu-latest

      - name: Build and push GPU Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.gpu
          push: true
          tags: |
            ghcr.io/bfds-project/bearing-fault-diagnosis-system-webui:gpu-${{ env.new_version }}
            ghcr.io/bfds-project/bearing-fault-diagnosis-system-webui:gpu-latest

      - name: Push new Git tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag -a "v${{ env.new_version }}" -m "Release version ${{ env.new_version }}"
          git push origin "v${{ env.new_version }}"