name: Publish Docker Image to GitHub Container Registry

on:
  release:
    types: [published]  # 只有在发布时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 获取仓库代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 设置 Docker 版本
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 登录 GitHub 容器注册表
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}  # GitHub 用户名
          password: ${{ secrets.GITHUB_TOKEN }}  # GitHub 令牌

      # 构建 Docker 镜像并推送到 GitHub 容器注册表
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile  # 如果您的 Dockerfile 有不同的路径，请更改此路径
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/bearing-fault-diagnosis-system-webui:${{ github.ref_name }}  # 使用版本号作为标签
