name: auto docker

on:
  release:
    types: [published]

permissions:
  contents: read      # 允许 actions/checkout 读取仓库
  packages: write     # 允许向 GHCR 推送镜像

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest tag
        id: get_latest_tag
        run: |
          # 获取最新的标签
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0")
          echo "Latest tag: $latest_tag"

          # 提取版本号（不递增）
          version=$(echo $latest_tag | grep -oE '[0-9]+\.[0-9]+' || echo "0.0")
          new_version="${version}"

          # 输出版本号
          echo "New version: $new_version"
          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Build and push CPU Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.cpu
          push: true
          tags: |
            ghcr.io/bfds-project/bearing-fault-diagnosis-system-webui:cpu${{ env.new_version }}
            ghcr.io/bfds-project/bearing-fault-diagnosis-system-webui:cpu-latest

      - name: Build and push GPU Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.gpu
          push: true
          tags: |
            ghcr.io/bfds-project/bearing-fault-diagnosis-system-webui:gpu${{ env.new_version }}
            ghcr.io/bfds-project/bearing-fault-diagnosis-system-webui:gpu-latest