name: auto docker

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "cpu0.0")
          echo "Latest tag: $latest_tag"
          version=$(echo $latest_tag | grep -oE '[0-9]+\.[0-9]+' || echo "0.0")
          major=$(echo $version | cut -d. -f1)
          minor=$(echo $version | cut -d. -f2)
          new_minor=$((minor + 1))
          new_version="${major}.${new_minor}"
          echo "New version: $new_version"
          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Build and push CPU Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.cpu
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/bearing-fault-diagnosis-system-webui:cpu-${{ env.new_version }}
            ghcr.io/${{ github.repository_owner }}/bearing-fault-diagnosis-system-webui:cpu-latest

      - name: Build and push GPU Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.gpu
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/bearing-fault-diagnosis-system-webui:gpu-${{ env.new_version }}
            ghcr.io/${{ github.repository_owner }}/bearing-fault-diagnosis-system-webui:gpu-latest