name: Sync with Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 同步到 Hugging Face Space
        uses: alex-bene/huggingface-space-sync-action@v0.1
        with:
          github_repo_id: ${{ github.repository }}
          github_branch: main
          yaml_header_path: docs/hf_space_metadata.yml
          huggingface_repo_id: BFDS-Project/Bearing-Fault-Diagnosis-System-Web
          hf_username: Str0keOOOO
          hf_token: ${{ secrets.HF_TOKEN }}
          force: true
