name: Sync with Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 完整克隆仓库历史记录

      - name: 同步到 Hugging Face Space
        run: |
          mv requirements-cpu.txt requirements.txt
          echo '---'|cat - docs/hf_space_metadata.yml > README_sp.md
          echo -e '---\n'|cat - README.md >> README_sp.md
          rm README.md
          mv README_sp.md README.md
          git add README.md requirements.txt
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git commit -m "Added yaml header on README for HF Space" || echo "No changes to commit"
          git push --force https://Str0keOOOO:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/BFDS-Project/Bearing-Fault-Diagnosis-System-Web main