jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 配置 Git 用户
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: 添加 Hugging Face Space 远程仓库
        run: |
          git remote add hf https://{{ secrets.HF_TOKEN }}@huggingface.co/BFDS-Project/Bearing-Fault-Diagnosis-System-Web
          git fetch hf main

      - name: 合并 Hugging Face Space 最新内容
        run: |
          git merge hf/main --allow-unrelated-histories -m "Merge Hugging Face Space changes"

      - name: 同步到 Hugging Face Space
        uses: alex-bene/huggingface-space-sync-action@v0.1
        with:
          github_repo_id: ${{ github.repository }}
          github_branch: main
          yaml_header_path: docs/hf_space_metadata.yml
          huggingface_repo_id: BFDS-Project/Bearing-Fault-Diagnosis-System-Web
          hf_username: Str0keOOOO
          hf_token: ${{ secrets.HF_TOKEN }}